name: Build and Deploy Blog
on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'index.html'
      - 'style.css'
      - 'main.js'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm init -y
          npm install gray-matter@4.0.3 reading-time@1.5.0 marked@4.3.0 prismjs@1.29.0 node-fetch@2.7.0

      - name: Create Build Directory
        run: |
          mkdir -p build
          cp index.html build/
          cp style.css build/
          cp main.js build/

      - name: Fetch Author Info
        run: |
          cat << 'EOF' > scripts/fetch-author.js
          const fetch = require('node-fetch');
          const fs = require('fs');

          async function fetchGithubProfile() {
            const username = process.env.GITHUB_REPOSITORY.split('/')[0];
            const response = await fetch(`https://api.github.com/users/${username}`);
            const data = await response.json();
            
            const author = {
              name: data.name || username,
              avatar: data.avatar_url,
              bio: data.bio,
              location: data.location,
              github: data.html_url,
              blog: data.blog,
              followers: data.followers
            };
            
            fs.writeFileSync('build/author.json', JSON.stringify(author, null, 2));
          }

          fetchGithubProfile().catch(console.error);
          EOF

      - name: Generate Posts Index
        run: |
          cat << 'EOF' > scripts/generate-index.js
          const fs = require('fs');
          const path = require('path');
          const matter = require('gray-matter');
          const readingTime = require('reading-time');
          const { marked } = require('marked');
          const Prism = require('prismjs');
          require('prismjs/components/prism-typescript');
          require('prismjs/components/prism-javascript');
          require('prismjs/components/prism-python');
          require('prismjs/components/prism-go');
          require('prismjs/components/prism-bash');
          require('prismjs/components/prism-json');

          marked.setOptions({
            highlight: function(code, lang) {
              if (Prism.languages[lang]) {
                return Prism.highlight(code, Prism.languages[lang], lang);
              }
              return code;
            }
          });

          const POSTS_DIR = 'posts';
          const BUILD_DIR = 'build';
          
          function getAllPosts() {
            const posts = [];
            if (!fs.existsSync(POSTS_DIR)) {
              console.log('Posts directory not found');
              return posts;
            }
            
            // Create posts directory in build
            if (!fs.existsSync(path.join(BUILD_DIR, 'posts'))) {
              fs.mkdirSync(path.join(BUILD_DIR, 'posts'));
            }
            
            const files = fs.readdirSync(POSTS_DIR);
            
            files.forEach(filename => {
              if (!filename.endsWith('.md') && !filename.endsWith('.mdx')) return;
              
              const filePath = path.join(POSTS_DIR, filename);
              const content = fs.readFileSync(filePath, 'utf-8');
              const { data, content: markdown } = matter(content);
              
              const readTime = readingTime(markdown);
              const html = marked(markdown);
              
              // Copy post to build directory
              fs.writeFileSync(path.join(BUILD_DIR, 'posts', filename), content);
              
              posts.push({
                title: data.title,
                date: data.date,
                tags: data.tags || [],
                path: `/posts/${filename}`,
                excerpt: data.excerpt || markdown.slice(0, 200) + '...',
                readingTime: readTime.text,
                content: html,
                lastModified: fs.statSync(filePath).mtime.toISOString()
              });
            });
            
            return posts.sort((a, b) => new Date(b.date) - new Date(a.date));
          }
          
          const posts = getAllPosts();
          fs.writeFileSync(path.join(BUILD_DIR, 'posts.json'), JSON.stringify(posts, null, 2));
          
          const tags = new Set();
          posts.forEach(post => post.tags.forEach(tag => tags.add(tag)));
          fs.writeFileSync(path.join(BUILD_DIR, 'tags.json'), JSON.stringify(Array.from(tags), null, 2));
          EOF
          
          mkdir -p scripts
          node scripts/fetch-author.js
          node scripts/generate-index.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true